CONFIG: additional packaging helpers, tutorial test helper
- bin/tools/create-mpi-config to query/write values for system openmpi.
  In some cases this can be used to avoid an mpicc requirement at runtime.

- adjust openfoam session to latest version,
  including -test-tutorial forwarding.

- adjust foamConfigurePaths to latest version

- removal of gperftools default config, as per develop

diff --git a/bin/foamEtcFile b/bin/foamEtcFile
--- a/bin/foamEtcFile
+++ b/bin/foamEtcFile
@@ -7,14 +7,13 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2011-2016 OpenFOAM Foundation
-#     Copyright (C) 2017-2018 OpenCFD Ltd.
+#     Copyright (C) 2017-2020 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM, licensed under GNU General Public License
-#     <http://www.gnu.org/licenses/>.
+#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
 #
 # Script
-#     foamEtcFile
+#     bin/foamEtcFile
 #
 # Description
 #     Locate user/group/other file as per '#includeEtc'.
@@ -33,7 +32,13 @@
 #     \endcode
 #
 # Environment
-#     - WM_PROJECT_SITE         (unset defaults to PROJECT/site)
+#     FOAM_CONFIG_ETC
+#         Alternative etc directory for shipped files
+#
+#     FOAM_CONFIG_MODE
+#         Fallback search mode for etc files. Unset is the same as "ugo".
+#
+#     WM_PROJECT_SITE         (unset defaults to PROJECT/site)
 #
 # Note
 #     This script must exist in the project 'bin' directory
@@ -46,8 +51,8 @@
 printHelp() {
     cat<<USAGE
 
-Usage: foamEtcFile [OPTION] fileName [-- args]
-       foamEtcFile [OPTION] [-list|-list-test] [fileName]
+Usage: ${0##*/} [OPTION] fileName [-- args]
+       ${0##*/} [OPTION] [-list|-list-test] [fileName]
 
 options:
   -all (-a)         Return all files (otherwise stop after the first match)
@@ -61,8 +66,8 @@ options:
   -config           Add config directory prefix for shell type:
                         with -csh* for a config.csh/ prefix
                         with -sh*  for a config.sh/ prefix
-  -show-api         Print api value from wmake/rules, or meta-info and exit
-  -show-patch       Print patch value from meta-info and exit
+  -show-api         Print META-INFO api value and exit
+  -show-patch       Print META-INFO patch value and exit
   -with-api=NUM     Specify alternative api value to search with
   -quiet (-q)       Suppress all normal output
   -silent (-s)      Suppress stderr, except -csh-verbose, -sh-verbose output
@@ -106,64 +111,40 @@ projectDir="$(\cd $(dirname $binDir) && \pwd -L)"   # Project dir
 
 userDir="$HOME/.OpenFOAM"                           # As per foamVersion.H
 groupDir="${WM_PROJECT_SITE:-$projectDir/site}"     # As per foamVersion.H
+optMode=ugo                                         # Default search = 'ugo'
+
+# Environment overrides
+case "$FOAM_CONFIG_MODE" in ([ugo]*) optMode="$FOAM_CONFIG_MODE" ;; esac
+
+# Verify validity of FOAM_CONFIG_ETC
+if [ -n "$FOAM_CONFIG_ETC" ]
+then
+    if [ ! -d "$FOAM_CONFIG_ETC" ] || [ "$FOAM_CONFIG_ETC" = "$projectDir/etc" ]
+    then
+        # Bad directory or redundant value
+        unset FOAM_CONFIG_ETC
+    fi
+fi
 
 #-------------------------------------------------------------------------------
 
-# The API locations. See wmake/wmakeBuildInfo
-rulesFile="$projectDir/wmake/rules/General/general"
-metaInfoDir="$projectDir/META-INFO"
-
-# Get api from rules/General/general
-#
-# Failure modes:
-# - No api information (can't find file etc).
-#   -> Fatal for building, but could be OK for a stripped down version
-#
-# Fallback. Get from api-info
-#
-getApi()
+# Get a value from META-INFO/api-info
+# $1 : keyword
+getApiInfo()
 {
-    local value
-
-    value="$(sed -ne '/^ *#/!{ /WM_VERSION.*OPENFOAM=/{ s@^.*OPENFOAM= *\([0-9][0-9]*\).*@\1@p; q }}' $rulesFile 2>/dev/null)"
-    if [ -z "$value" ] && [ -f "$metaInfoDir/api-info" ]
-    then
-        # Fallback. Get from api-info
-        value="$(sed -ne 's@^ *api *= *\([0-9][0-9]*\).*@\1@p' $metaInfoDir/api-info 2>/dev/null)"
-    fi
+    value="$(sed -ne 's@^'"$1"' *= *\([0-9][0-9]*\).*@\1@p' "$projectDir"/META-INFO/api-info 2>/dev/null)"
 
     if [ -n "$value" ]
     then
         echo "$value"
     else
-        return 1
-    fi
-}
-
-
-# Get patch from meta-info / api-info
-#
-# Failure modes:
-# - No patch information (can't find file etc).
-#
-getPatchLevel()
-{
-    local value
-
-    # Fallback. Get from api-info
-    value="$(sed -ne 's@^ *patch *= *\([0-9][0-9]*\).*@\1@p' $metaInfoDir/api-info 2>/dev/null)"
-
-    if [ -n "$value" ]
-    then
-        echo "$value"
-    else
+        echo "Could not determine OPENFOAM '$1' value" 1>&2
         return 1
     fi
 }
 
 
 #-------------------------------------------------------------------------------
-optMode=ugo         # Default mode is always 'ugo'
 unset shellOutput verboseOutput
 unset optAll optConfig optList projectApi
 
@@ -174,14 +155,12 @@ do
     -h | -help*)
         printHelp
         ;;
-    -show-api)
-        # Show API and exit
-        getApi
+    -show-api)  # Show API and exit
+        getApiInfo api
         exit $?
         ;;
-    -show-patch)
-        # Show patch level and exit
-        getPatchLevel
+    -show-patch)  # Show patch level and exit
+        getApiInfo patch
         exit $?
         ;;
     -with-api=*)
@@ -208,7 +187,7 @@ do
     -config)
         optConfig=true
         ;;
-    -mode=[ugoa]*)
+    -mode=[ugo]*)
         optMode="${1#*=}"
         ;;
     -m | -mode)
@@ -216,7 +195,7 @@ do
         shift
         # Sanity check. Handles missing argument too.
         case "$optMode" in
-        ([ugoa]*)
+        ([ugo]*)
             ;;
         (*)
             die "invalid mode '$optMode'"
@@ -257,8 +236,7 @@ done
 #-------------------------------------------------------------------------------
 
 # Establish the API value
-[ -n "$projectApi" ] || projectApi=$(getApi)
-
+[ -n "$projectApi" ] || projectApi=$(getApiInfo api)
 
 # Split arguments into filename (for searching) and trailing bits for shell eval
 # Silently remove leading ~OpenFOAM/ (as per Foam::findEtcFile)
@@ -293,23 +271,23 @@ fi
 
 # Define the various places to be searched:
 unset dirList
-case "$optMode" in (*[au]*) # (A)ll or (U)ser
+case "$optMode" in (*[u]*) # (U)ser
     dirList="$dirList $userDir/$projectApi $userDir"
     ;;
 esac
 
-case "$optMode" in (*[ag]*) # (A)ll or (G)roup == site
+case "$optMode" in (*[g]*) # (G)roup == site
     dirList="$dirList $groupDir/$projectApi/etc $groupDir/etc"
     ;;
 esac
 
-case "$optMode" in (*[ao]*) # (A)ll or (O)ther == shipped
-    dirList="$dirList $projectDir/etc"
+case "$optMode" in (*[o]*) # (O)ther == shipped
+    dirList="$dirList $FOAM_CONFIG_ETC $projectDir/etc"
     ;;
 esac
 set -- $dirList
 
-[ "$#" -ge 1 ] || die "No directories to scan. Programming error?"
+[ "$#" -ge 1 ] || die "No directories to scan. Programming or user error?"
 exitCode=2  # Fallback is a FileNotFound error
 
 
@@ -318,7 +296,7 @@ exitCode=2  # Fallback is a FileNotFound error
 #
 
 # Special handling of config.sh/ , config.csh/ directories
-if [ -n "$optConfig" -a -n "$shellOutput" -a -n "$fileName" ]
+if [ -n "$optConfig" ] && [ -n "$shellOutput" ] && [ -n "$fileName" ]
 then
     case "$shellOutput" in
     csh*)
