BACKPORT: installation helpers from v2012
BACKPORT: AllwmakeParseArguments prefix handling from v2012

diff --git a/wmake/scripts/AllwmakeParseArguments b/wmake/scripts/AllwmakeParseArguments
--- a/wmake/scripts/AllwmakeParseArguments
+++ b/wmake/scripts/AllwmakeParseArguments
@@ -6,11 +6,10 @@
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
 #     Copyright (C) 2014-2017 OpenFOAM Foundation
-#     Copyright (C) 2019 OpenCFD Ltd.
+#     Copyright (C) 2019-2020 OpenCFD Ltd.
 #------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM, licensed under GNU General Public License
-#     <http://www.gnu.org/licenses/>.
+#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
 #
 # File
 #     wmake/scripts/AllwmakeParseArguments
@@ -22,14 +21,35 @@
 #     # Parse the arguments by sourcing this script
 #     . ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
 #
+# Parsed options (make)
+#     -k | -keep-going | -non-stop
+#     -j | -jN | -j N
+#
+# Parsed options (wmake)
+#     -debug
+#     -q | -queue
+#     -module-prefix=...
+#         Exports FOAM_MODULE_PREFIX value.
+#         Unsets FOAM_MODULE_APPBIN, FOAM_MODULE_LIBBIN.
+#         Handles (user|group|openfoam) or (u|g|o) as per foamEtcFile,
+#         or absolute/relative paths
+#
+# Parsed options (special)
+#     -l | -log | -log=FILE
+#     -prefix=...   same as -module-prefix=...
+#
 #------------------------------------------------------------------------------
-
-if [ -z "$WM_PROJECT_DIR" ]
-then
-    echo "$Script error: The OpenFOAM environment is not set."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+# Check environment
+[ -d "$WM_PROJECT_DIR" ] || {
+    exec 1>&2
+    echo "$0"
+    echo "Error encountered:"
+    echo "    The OpenFOAM environment not set or incorrect."
+    echo "    Check your setup."
+    echo
     exit 1
-fi
+}
+
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
@@ -40,13 +60,18 @@ Executing ${0##*/} is equivalent to
 
    wmake -all [OPTIONS]
 
-With these additional options:
-   -l | -log | -log=name
+With additional options:
+    -l | -log       Tee output to log.\$WM_OPTIONS
+    -log=FILE       Tee output to given filename
+    -prefix=...     Define FOAM_MODULE_PREFIX (same as wmake -module-prefix)
+    -no-recursion   Prevent recursive call (do NOT call 'wmake -all')
+    -fromWmake      Same as -no-recursion
+
+See
+    wmake -help (or wmake -help-full)
 
 USAGE
-
-    wmake -help
-    exit 0
+    exit 0  # clean exit
 }
 
 
@@ -54,7 +79,8 @@ USAGE
 # Parse the arguments and options
 #------------------------------------------------------------------------------
 
-unset fromWmake optDebug optLog optQueue
+unset optDebug optLog optNonRecursive optQueue
+unset optWmakeFrontend
 
 for arg in "$@"
 do
@@ -65,41 +91,81 @@ do
     -h | -help*)
         usage
         ;;
-    -fromWmake)
-        # If called from wmake (to avoid recursion)
-        fromWmake=true
+
+    -no-recurs* | -fromWmake)
+        # Avoid recursion (eg, if called from wmake)
+        optNonRecursive=true
+        # Pass onwards to other Allwmake scripts
         ;;
+
+    -module-prefix=* | -prefix=* | --prefix=*)
+        # As per setModulePrefix (wmakeFunctions)
+        export FOAM_MODULE_PREFIX="${arg#*=}"
+        case "$FOAM_MODULE_PREFIX" in
+        # Prefix: user
+        (u | user)      FOAM_MODULE_PREFIX="${FOAM_USER_LIBBIN%/*}" ;;
+
+        # Prefix: group
+        (g | group)     FOAM_MODULE_PREFIX="${FOAM_SITE_LIBBIN%/*}" ;;
+
+        # Prefix: openfoam (other)
+        (o | openfoam)  FOAM_MODULE_PREFIX="${FOAM_LIBBIN%/*}" ;;
+
+        # Prefix: false (ie, 'disabled')
+        (false) FOAM_MODULE_PREFIX=false ;;
+
+        # Prefix: directory (absolute or relative)
+        (*)
+            : "${FOAM_MODULE_PREFIX:=/usr/local}"  # Fallback (autoconf-like)
+
+            # Require absolute path
+            [ "${FOAM_MODULE_PREFIX#/}" != "${FOAM_MODULE_PREFIX}" ] || \
+                FOAM_MODULE_PREFIX="${PWD}/${FOAM_MODULE_PREFIX}"
+            ;;
+        esac
+
+        # Avoid potential conflicts
+        unset FOAM_MODULE_APPBIN FOAM_MODULE_LIBBIN
+        echo "Module prefix = ${FOAM_MODULE_PREFIX:-[]}" 1>&2
+        continue    # Argument handled, remove it
+        ;;
+
     -k | -keep-going | -non-stop)
         # Keep going, ignoring errors
         export WM_CONTINUE_ON_ERROR=true
-        continue    # Permanently remove arg
+        continue    # Argument handled, remove it
         ;;
+
     -l | -log)
-        optLog="log.${WM_OPTIONS:-Allwmake}"
-        continue    # Permanently remove arg
+        optLog="log.${WM_OPTIONS:-build}"
+        continue    # Argument handled, remove it
         ;;
+
     -log=*)
         optLog="${arg##*=}"
         if [ -d "$optLog" ]
         then
-            optLog="${optLog%/}/log.${WM_OPTIONS:-Allwmake}"
+            optLog="${optLog%/}/log.${WM_OPTIONS:-build}"
         elif [ -z "$optLog" ]
         then
-            optLog="log.${WM_OPTIONS:-Allwmake}"
+            optLog="log.${WM_OPTIONS:-build}"
         fi
-        continue    # Permanently remove arg
+        continue    # Argument handled, remove it
         ;;
+
     -debug)
         optDebug="-debug"
-        continue    # Permanently remove arg
+        continue    # Argument handled, remove it
         ;;
+
     -q | -queue)
         optQueue="-queue"
-        continue    # Permanently remove arg
+        continue    # Argument handled, remove it
         ;;
+
     lib | libo | libso | dep | objects)
         # Target type
-        targetType=$arg
+        targetType="$arg"
         ;;
     esac
 
@@ -112,20 +178,22 @@ done
 # Execute wmake -all if not called from wmake
 #------------------------------------------------------------------------------
 
-if [ -z "$fromWmake" ]
+if [ -z "$optNonRecursive" ]
 then
     if [ -z "$optLog" ]
     then
-        exec wmake -all $optQueue $*
+        exec wmake $optWmakeFrontend -all \
+            $optDebug $optQueue $*
         exit $? # Unneeded, but just in case something went wrong
     else
         echo "Logging wmake -all output to '$optLog'" 1>&2
         echo 1>&2
-        exec wmake -all $optDebug $optQueue $* 2>&1 | /usr/bin/tee $optLog
+        exec wmake $optWmakeFrontend -all \
+            $optDebug $optQueue $* 2>&1 | /usr/bin/tee $optLog
         # Need to cleanup after the tee
         rc=$? # Error code from tee (not wmake), but not entirely important
         echo "Done logging to '$optLog'" 1>&2
-        exit $rc
+        exit "$rc"
     fi
 fi
 
@@ -144,7 +212,8 @@ fi
 # Cleanup local variables and functions
 #------------------------------------------------------------------------------
 
-unset fromWmake optDebug optLog optQueue
+unset optWmakeFrontend
+unset optNonRecursive optDebug optLog optQueue
 unset -f usage
 
 
