BACKPORT: adjust wmake/scripts/*Functions according to v2006
- simplifies maintenance of detection scripts

diff --git a/wmake/scripts/AllwmakeParseArguments b/wmake/scripts/AllwmakeParseArguments
--- a/wmake/scripts/AllwmakeParseArguments
+++ b/wmake/scripts/AllwmakeParseArguments
@@ -2,12 +2,14 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2014-2017 OpenFOAM Foundation
+#   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
+#     Copyright (C) 2014-2017 OpenFOAM Foundation
+#     Copyright (C) 2019-2020 OpenCFD Ltd.
+#------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM, licensed under GNU General Public License
-#     <http://www.gnu.org/licenses/>.
+#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
 #
 # File
 #     wmake/scripts/AllwmakeParseArguments
@@ -17,16 +19,37 @@
 #
 # Usage
 #     # Parse the arguments by sourcing this script
-#     . $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
+#     . ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
+#
+# Parsed options (make)
+#     -k | -keep-going | -non-stop
+#     -j | -jN | -j N
+#
+# Parsed options (wmake)
+#     -debug
+#     -q | -queue
+#     -module-prefix=...
+#         Exports FOAM_MODULE_PREFIX value.
+#         Unsets FOAM_MODULE_APPBIN, FOAM_MODULE_LIBBIN.
+#         Handles (user|group|openfoam) or (u|g|o) as per foamEtcFile,
+#         or absolute/relative paths
+#
+# Parsed options (special)
+#     -l | -log | -log=FILE
+#     -prefix=...   same as -module-prefix=...
 #
 #------------------------------------------------------------------------------
-
-if [ -z "$WM_PROJECT_DIR" ]
-then
-    echo "$Script error: The OpenFOAM environment is not set."
-    echo "    Check the OpenFOAM entries in your dot-files and source them."
+# Check environment
+[ -d "$WM_PROJECT_DIR" ] || {
+    exec 1>&2
+    echo "$0"
+    echo "Error encountered:"
+    echo "    The OpenFOAM environment not set or incorrect."
+    echo "    Check your setup."
+    echo
     exit 1
-fi
+}
+
 usage() {
     exec 1>&2
     while [ "$#" -ge 1 ]; do echo "$1"; shift; done
@@ -37,13 +60,18 @@ Executing ${0##*/} is equivalent to
 
    wmake -all [OPTIONS]
 
-With these additional options:
-   -l | -log | -log=name
+With additional options:
+    -l | -log       Tee output to log.\$WM_OPTIONS
+    -log=NAME       Tee output to given filename
+    -prefix=...     Define FOAM_MODULE_PREFIX (same as wmake -module-prefix)
+    -no-recursion   Prevent recursive call (do NOT call 'wmake -all')
+    -fromWmake      Same as -no-recursion
+
+See
+    wmake -help (or wmake -help-full)
 
 USAGE
-
-    wmake -help
-    exit 0
+    exit 0  # clean exit
 }
 
 
@@ -51,7 +79,7 @@ USAGE
 # Parse the arguments and options
 #------------------------------------------------------------------------------
 
-unset fromWmake optLog optQueue
+unset optDebug optLog optNonRecursive optPrefix optQueue
 
 for arg in "$@"
 do
@@ -62,37 +90,83 @@ do
     -h | -help*)
         usage
         ;;
-    -fromWmake)
-        # If called from wmake (to avoid recursion)
-        fromWmake=true
+
+    -no-recurs* | -fromWmake)
+        # Avoid recursion (eg, if called from wmake)
+        optNonRecursive=true
+        # Pass onwards to other Allwmake scripts
         ;;
-    -k | -non-stop)
-        # Non-stop compilation, ignoring errors
+
+    -module-prefix=* | -prefix=* | --prefix=*)
+        optPrefix="${arg#*=}"
+        case "$optPrefix" in
+        # Prefix: user
+        (u | user)
+            export FOAM_MODULE_PREFIX="${FOAM_USER_LIBBIN%/*}"
+            ;;
+
+        # Prefix: group
+        (g | group)
+            export FOAM_MODULE_PREFIX="${FOAM_SITE_LIBBIN%/*}"
+            ;;
+
+        # Prefix: openfoam (other)
+        (o | openfoam)
+            export FOAM_MODULE_PREFIX="${FOAM_LIBBIN%/*}"
+            ;;
+
+        # Prefix: custom (absolute or relative)
+        (*)
+            export FOAM_MODULE_PREFIX="$optPrefix"
+            : "${FOAM_MODULE_PREFIX:=/usr/local}"  # Default (autoconf)
+
+            # Require absolute path
+            [ "${FOAM_MODULE_PREFIX#/}" != "${FOAM_MODULE_PREFIX}" ] || \
+                FOAM_MODULE_PREFIX="${PWD}/${FOAM_MODULE_PREFIX}"
+            ;;
+        esac
+
+        unset FOAM_MODULE_APPBIN FOAM_MODULE_LIBBIN
+        echo "Module prefix = $FOAM_MODULE_PREFIX" 1>&2
+        continue    # Handled argument
+        ;;
+
+    -k | -keep-going | -non-stop)
+        # Keep going, ignoring errors
         export WM_CONTINUE_ON_ERROR=true
         continue    # Permanently remove arg
         ;;
+
     -l | -log)
-        optLog="log.${WM_OPTIONS:-Allwmake}"
+        optLog="log.${WM_OPTIONS:-build}"
         continue    # Permanently remove arg
         ;;
+
     -log=*)
         optLog="${arg##*=}"
         if [ -d "$optLog" ]
         then
-            optLog="${optLog%/}/log.${WM_OPTIONS:-Allwmake}"
+            optLog="${optLog%/}/log.${WM_OPTIONS:-build}"
         elif [ -z "$optLog" ]
         then
-            optLog="log.${WM_OPTIONS:-Allwmake}"
+            optLog="log.${WM_OPTIONS:-build}"
         fi
         continue    # Permanently remove arg
         ;;
-    -q | -queue)
-        optQueue="-q"
+
+    -debug)
+        optDebug="-debug"
         continue    # Permanently remove arg
         ;;
+
+    -q | -queue)
+        optQueue="-queue"
+        continue    # Permanently remove arg
+        ;;
+
     lib | libo | libso | dep | objects)
         # Target type
-        targetType=$arg
+        targetType="$arg"
         ;;
     esac
 
@@ -105,20 +179,20 @@ done
 # Execute wmake -all if not called from wmake
 #------------------------------------------------------------------------------
 
-if [ -z "$fromWmake" ]
+if [ -z "$optNonRecursive" ]
 then
     if [ -z "$optLog" ]
     then
-        exec wmake -all $optQueue $*
+        exec wmake -all $optDebug $optQueue $*
         exit $? # Unneeded, but just in case something went wrong
     else
         echo "Logging wmake -all output to '$optLog'" 1>&2
         echo 1>&2
-        exec wmake -all $optQueue $* 2>&1 | /usr/bin/tee $optLog
+        exec wmake -all $optDebug $optQueue $* 2>&1 | /usr/bin/tee $optLog
         # Need to cleanup after the tee
         rc=$? # Error code from tee (not wmake), but not entirely important
         echo "Done logging to '$optLog'" 1>&2
-        exit $rc
+        exit "$rc"
     fi
 fi
 
@@ -137,7 +211,7 @@ fi
 # Cleanup local variables and functions
 #------------------------------------------------------------------------------
 
-unset fromWmake optLog optQueue
+unset optNonRecursive optDebug optLog optPrefix optQueue
 unset -f usage
 
 
diff --git a/wmake/scripts/paraviewFunctions b/wmake/scripts/paraviewFunctions
--- a/wmake/scripts/paraviewFunctions
+++ b/wmake/scripts/paraviewFunctions
@@ -2,12 +2,13 @@
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
-#   \\  /    A nd           | Copyright (C) 2018 OpenCFD Ltd.
+#   \\  /    A nd           | www.openfoam.com
 #    \\/     M anipulation  |
 #------------------------------------------------------------------------------
+#     Copyright (C) 2018-2020 OpenCFD Ltd.
+#------------------------------------------------------------------------------
 # License
-#     This file is part of OpenFOAM, licensed under GNU General Public License
-#     <http://www.gnu.org/licenses/>.
+#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
 #
 # Script
 #     paraviewFunctions
@@ -17,12 +18,12 @@
 #     Setup of variables for creating ParaView plugins
 #
 # Requires
-#     ParaView_DIR  (unless system)
-#     PV_PLUGIN_PATH
+#     ParaView_DIR   (unless system)
+#     PV_PLUGIN_PATH (or rely on automatic mechanism)
 #
 # Provides Functions
-#     have_pvplugin_support, no_paraview, echo_paraview
-#     cmakeVtk, cmakePv
+#     get_pvplugin_api, have_pvplugin_support, no_paraview, echo_paraview
+#     cmakeVtk, cmakePv, cmakePvInstall
 #
 # Variables on success
 #     HAVE_PVPLUGIN_SUPPORT
@@ -35,8 +36,8 @@
 #     paraview-major.minor encoded in its name.
 #
 #------------------------------------------------------------------------------
-. $WM_PROJECT_DIR/wmake/scripts/sysFunctions # General system functions
-. $WM_PROJECT_DIR/wmake/scripts/cmakeFunctions  # Require cmake functions
+. ${WM_PROJECT_DIR:?}/wmake/scripts/sysFunctions    # General system functions
+. ${WM_PROJECT_DIR:?}/wmake/scripts/cmakeFunctions  # Require cmake functions
 
 #------------------------------------------------------------------------------
 
@@ -45,7 +46,6 @@ no_paraview()
 {
     unset HAVE_PVPLUGIN_SUPPORT FOAM_PV_PLUGIN_LIBBIN
     unset PARAVIEW_API PARAVIEW_INC_DIR
-    return 0
 }
 
 
@@ -53,42 +53,123 @@ no_paraview()
 echo_paraview()
 {
     echo "paraview=${HAVE_PVPLUGIN_SUPPORT:-false}"
-    echo "root=$ParaView_DIR"
-    echo "include=$PARAVIEW_INC_DIR"
-    echo "plugin=$FOAM_PV_PLUGIN_LIBBIN"
+    echo "root=\"$ParaView_DIR\""
+    echo "include=\"$PARAVIEW_INC_DIR\""
+    echo "plugin=\"$FOAM_PV_PLUGIN_LIBBIN\""
     echo "api=$PARAVIEW_API"
 }
 
 
 # CMake into objectsDir with VTK_DIR dependency
+# 1 - sourceDir
+# 2.. optional cmake defines
 cmakeVtk()
 {
-    cmakeVersioned "VTK_DIR=$VTK_DIR" "$1"
+    cmakeVersioned "VTK_DIR=$VTK_DIR" "$@"
 }
 
 
 # CMake into objectsDir with ParaView_DIR dependency
+# 1 - sourceDir
+# 2.. optional cmake defines
 cmakePv()
 {
-    cmakeVersioned "ParaView_DIR=$ParaView_DIR" "$1"
+    cmakeVersioned "ParaView_DIR=$ParaView_DIR" "$@"
 }
 
-#
+# CMake into objectsDir with ParaView_DIR dependency
+# 1 - sourceDir
+# 2.. optional cmake defines
+cmakePvInstall()
+{
+    cmakeVersionedInstall "ParaView_DIR=$ParaView_DIR" "$@"
+}
+
+
 # Build library - use sentinel file(s) to handle paraview version changes
+# Some difficulty handling different installation options as well
+# as wmake options, so only handle build/configure information for now
 #
+# 1 - libName
+# 2... build/configure information
+#
+# Similar to wmakeVersioned
 wmakeLibPv()
 {
     local depend="ParaView_DIR=$ParaView_DIR"
+    local libName="$1"
+    shift 1
     local sentinel
 
-    for libName
-    do
-        sentinel=$(sameDependency "$depend" $libName) || \
-            wclean $libName
+    sentinel=$(sameDependency "$libName" "$depend" $@) || \
+        wclean "$libName"
 
-        wmake $targetType $libName \
-        && echo "$depend" > ${sentinel:-/dev/null}
-    done
+    wmake $targetType "$libName" \
+    && storeDependency "$sentinel" "$depend" $@
+}
+
+# Get ParaView API from given path.
+# Eg, "/path/paraview-dir/paraview-5.6" -> "5.6"
+#
+# Or the output from `paraview --version`
+# Eg, "paraview version 5.6.3" -> "5.6"
+#
+# 1 - the input path ending with paraview-x.y, or paraview --version information
+#
+# On success, return 0 and echo value
+#
+get_pvapi()
+{
+    local pv_api
+
+    # Extract paraview major+minor version from the directory name
+    # From /path/paraview-5.6 -> 5.6
+    pv_api=$(echo "${1:-none}" | \
+        sed -ne 's@^.*/@@;s@^[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\).*$@\1@p')
+
+    if [ -z "$pv_api" ]
+    then
+        # Extract paraview major+minor version from "paraview --version" information
+        pv_api=$(echo "${1:-none}" | \
+            sed -ne 's@^.*version *\([0-9][0-9]*\.[0-9][0-9]*\).*$@\1@p')
+    fi
+
+    [ -n "$pv_api" ] || return 1
+
+    # OK
+    echo "$pv_api"
+}
+
+
+# Extract ParaView plugin api number from PV_PLUGIN_PATH
+# On success, return 0 and export variables
+# -> FOAM_PV_PLUGIN_LIBBIN, PARAVIEW_API
+#
+get_pvplugin_api()
+{
+    # OK
+    unset FOAM_PV_PLUGIN_LIBBIN  PARAVIEW_API
+    local pv_api targetDir
+
+    # The OpenFOAM plugin must be the first in PV_PLUGIN_PATH
+    # and must have the paraview major+minor version encoded in its name!
+    # Eg, PV_PLUGIN_PATH="$FOAM_LIBBIN/paraview-5.5"
+
+    # Get the first entry from PV_PLUGIN_PATH=dir1;dir2;...
+    targetDir="${PV_PLUGIN_PATH##;}"
+    targetDir="${targetDir%%;*}"
+
+    # Extract paraview major+minor version from directory name
+    # From /path/paraview-5.6 -> 5.6
+    pv_api=$(get_pvapi "$targetDir")
+
+    [ -n "$pv_api" ] || return 1
+
+    # OK
+    export FOAM_PV_PLUGIN_LIBBIN="$targetDir"
+    export PARAVIEW_API="$pv_api"
+
+    return 0 # success
 }
 
 
@@ -101,46 +182,51 @@ wmakeLibPv()
 #
 have_pvplugin_support()
 {
-    local header settings warn pv_api installDir binDir includeDir targetDir
-    warn="==> skip paraview-plugin"
+    local warn="==> skip paraview-plugin"
+    local settings pv_api pv_executable installDir binDir includeDir targetDir
 
     # Trivial check
-    command -v cmake > /dev/null 2>&1 || {
+    command -v cmake >/dev/null || {
         echo "$warn (no cmake)"
         return 1
     }
 
+    if get_pvplugin_api
+    then
+        targetDir="$FOAM_PV_PLUGIN_LIBBIN"
+        pv_api="$PARAVIEW_API"
+    fi
+    unset FOAM_PV_PLUGIN_LIBBIN PARAVIEW_API
 
-    # The OpenFOAM plugin must be the first in PV_PLUGIN_PATH
-    # and must have the paraview major+minor version encoded in its name!
-    # Eg, PV_PLUGIN_PATH="$FOAM_LIBBIN/paraview-5.5"
+    # Probably not needed...
+    # if [ -z "$targetDir" ] || [ -z "$pv_api" ]
+    # then
+    #     echo "$warn (could not determine target or major.minor version)"
+    #     echo "    PV_PLUGIN_PATH=${PV_PLUGIN_PATH:-???}"
+    #     return 1
+    # fi
 
-    # Get the first entry from PV_PLUGIN_PATH=dir1;dir2;...
-    targetDir="${PV_PLUGIN_PATH##;}"
-    targetDir="${targetDir%%;*}"
-
-    # Extract the paraview major+minor version from the directory name
-    # From /path/paraview-5.6 -> 5.6
-    pv_api=$(echo "$targetDir" | \
-        sed -ne 's@^.*/@@;s/^[^0-9]*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/p')
-
-    [ -n "$targetDir" ] || {
-        echo "$warn (could not determine target)"
-        echo "    PV_PLUGIN_PATH=${PV_PLUGIN_PATH:-???}"
-        return 1
-    }
-
-    [ -n "$pv_api" ] || {
-        echo "$warn (could not determine major.minor version)"
-        return 1
-    }
-
-    # Header/library names
-    header="pqServerManagerModel.h"
+    # Include/library names
+    local header="pqServerManagerModel.h"
 
     if [ -n "$ParaView_DIR" ]
     then
         # ParaView_DIR defined. Look for include/
+
+        # Unless already known, get API value from include directory name
+        if [ -z "$pv_api" ]
+        then
+            for settings in $(find "$ParaView_DIR"/include -maxdepth 1 -name 'paraview-*' -type d)
+            do
+                pv_api=$(get_pvapi "$settings") && break
+            done
+
+            if [ -z "$pv_api" ]
+            then
+                echo "$warn (could not determine paraview major.minor version)"
+                return 1
+            fi
+        fi
 
         header=$(findFirstFile \
             "$ParaView_DIR/include/paraview-$pv_api/$header" \
@@ -150,17 +236,31 @@ have_pvplugin_support()
     else
         # No ParaView_DIR defined
         # - use location of 'paraview' to guess an equivalent ParaView_DIR
-        # - assume we can use paraview-config
+        # - assume paraview-config works, but might be removed too!
 
-        binDir="$(command -v paraview 2>/dev/null)"
-        binDir="${binDir%/*}"       # Eg, /usr/bin/paraview -> /usr/bin
-        installDir="${binDir%/*}"   # Eg, /usr/bin -> /usr
+        pv_executable="$(command -v paraview 2>/dev/null)" || {
+            echo "$warn (no paraview found?)"
+            return 2
+        }
+        binDir="${pv_executable%/*}"  # Eg, /usr/bin/paraview -> /usr/bin
+        installDir="${binDir%/*}"     # Eg, /usr/bin -> /usr
 
         case "$installDir" in
         (/*)    # An absolute path
             includeDir="$installDir/include"  # Eg, /usr -> /usr/include
         ;;
         esac
+
+        # Unless already known, get API value from `paraview --version` information
+        if [ -z "$pv_api" ]
+        then
+            pv_api=$(get_pvapi "$("$pv_executable" --version)")
+            if [ -z "$pv_api" ]
+            then
+                echo "$warn (could not determine paraview major.minor version)"
+                return 1
+            fi
+        fi
 
         header=$(findFirstFile \
             "$(paraview-config --include 2>/dev/null |sed -ne 's/^ *-I//p')/$header"\
@@ -173,15 +273,20 @@ have_pvplugin_support()
             )
     fi
 
+    # ----------------------------------
 
-    # Header found?
+    # Header
     [ -n "$header" ] || {
         [ -n "$warn" ] && echo "$warn (no header)"
         return 2
     }
 
+    # ----------------------------------
+
+    # OK
+    # Use FOAM_LIBBIN/paraview-maj.min as default
     export HAVE_PVPLUGIN_SUPPORT=true
-    export FOAM_PV_PLUGIN_LIBBIN="$targetDir"
+    export FOAM_PV_PLUGIN_LIBBIN="${targetDir:-$FOAM_LIBBIN/paraview-$pv_api}"
     export PARAVIEW_API="$pv_api"
     export PARAVIEW_INC_DIR="${header%/*}"      # Basename
 
@@ -192,11 +297,15 @@ have_pvplugin_support()
 # Force reset of old variables
 no_paraview
 
-# Testing
-if [ "$1" = "-test" ]
-then
+# Test/query
+case "$1" in
+-test)
     have_pvplugin_support
     echo_paraview
-fi
+    ;;
+-query)
+    ## query_paraview
+    ;;
+esac
 
 #------------------------------------------------------------------------------
