BACKPORT: align wmake have_* scripts with v2006
- simplify maintenance

diff --git a/wmake/scripts/have_scotch b/wmake/scripts/have_scotch
--- a/wmake/scripts/have_scotch
+++ b/wmake/scripts/have_scotch
@@ -14,13 +14,13 @@
 #     have_scotch
 #
 # Description
-#     Detection/setup of scotch
+#     Detection/setup of SCOTCH
 #
 # Requires
 #     config.sh/scotch
 #
 # Functions provided
-#     have_scotch, no_scotch, echo_scotch
+#     have_ptscotch, search_ptscotch
 #
 # Variables set on success
 #     HAVE_SCOTCH
@@ -28,18 +28,67 @@
 #     SCOTCH_INC_DIR
 #     SCOTCH_LIB_DIR
 #
+# Functions provided [Must call have_scotch first]
+#     have_ptscotch, search_ptscotch
+#
+# Variables set on success
+#     HAVE_PTSCOTCH
+#     PTSCOTCH_ARCH_PATH
+#     PTSCOTCH_INC_DIR
+#     PTSCOTCH_LIB_DIR
+#
+#
+# System files can be hiding in a large variety of locations
+#
+# ArchLinux
+# ---------
+#     scotch   include=/usr/include/ptscotch
+#
+#     ptscotch include=/usr/include/ptscotch
+#
+#
+# Debian/Ubuntu
+# -------------
+#     scotch   include=/usr/include/scotch-int32
+#     scotch   library=/usr/lib/x86_64-linux-gnu
+#
+#     ptscotch include=/usr/include/scotch-int32
+#     ptscotch library=/usr/lib/x86_64-linux-gnu
+#
+#
+# RedHat
+# ------
+#     scotch   include=/usr/include
+#     scotch   library=/usr/lib64
+#
+#     ptscotch include=/usr/include/openmpi-x86_64
+#     ptscotch library=/usr/lib64/openmpi/lib
+#
+# when MPI_ARCH_PATH=/usr/lib64/openmpi
+# and mpicc --showme:compile -> -I/usr/include/openmpi-x86_64
+#
+#
+# openSUSE
+# --------
+#     scotch   include=/usr/include
+#     scotch   library=/usr/lib64
+#
+#     ptscotch include=/usr/lib64/mpi/gcc/openmpi2/include
+#     ptscotch library=/usr/lib64/mpi/gcc/openmpi2/lib64
+#
+# when MPI_ARCH_PATH=/usr/lib64/mpi/gcc/openmpi2
+#
 #------------------------------------------------------------------------------
-. $WM_PROJECT_DIR/wmake/scripts/sysFunctions # General system functions
+. ${WM_PROJECT_DIR:?}/wmake/scripts/sysFunctions    # General system functions
 
 #------------------------------------------------------------------------------
 
-# Reset variables
+# Reset
 no_scotch()
 {
     unset HAVE_SCOTCH SCOTCH_ARCH_PATH SCOTCH_INC_DIR SCOTCH_LIB_DIR
     unset SCOTCH_VERSION
     unset HAVE_PTSCOTCH PTSCOTCH_ARCH_PATH PTSCOTCH_INC_DIR PTSCOTCH_LIB_DIR
-    return 0
 }
 
 
@@ -47,102 +96,86 @@ no_scotch()
 echo_scotch()
 {
     echo "scotch=${HAVE_SCOTCH:-false}"
-    echo "root=$SCOTCH_ARCH_PATH"
-    echo "include=$SCOTCH_INC_DIR"
-    echo "library=$SCOTCH_LIB_DIR"
+    echo "root=\"$SCOTCH_ARCH_PATH\""
+    echo "include=\"$SCOTCH_INC_DIR\""
+    echo "library=\"$SCOTCH_LIB_DIR\""
     echo
     echo "ptscotch=${HAVE_PTSCOTCH:-false}"
-    echo "root=$PTSCOTCH_ARCH_PATH"
-    echo "include=$PTSCOTCH_INC_DIR"
-    echo "library=$PTSCOTCH_LIB_DIR"
+    echo "root=\"$PTSCOTCH_ARCH_PATH\""
+    echo "include=\"$PTSCOTCH_INC_DIR\""
+    echo "library=\"$PTSCOTCH_LIB_DIR\""
 }
 
 
+# Search
+# $1 : prefix (*_ARCH_PATH, system, ...)
+#
 # On success, return 0 and export variables
 # -> HAVE_SCOTCH, SCOTCH_ARCH_PATH, SCOTCH_INC_DIR, SCOTCH_LIB_DIR
-have_scotch()
+search_scotch()
 {
-    local header library static label settings warn
-    warn="==> skip scotch"
+    local warn="==> skip scotch"
+    local incName="scotch.h"
+    local libName="libscotch"
+    local localDir="scotch-int$WM_LABEL_SIZE"
 
-    # Basic setup/checks
-    settings=$($WM_PROJECT_DIR/bin/foamEtcFile config.sh/scotch) || {
-        [ -n "$warn" ] && echo "$warn (no config.sh/scotch settings)"
-        return 1
-    }
-    . $settings
-    if isNone "$SCOTCH_ARCH_PATH"
+    local prefix="${1:-system}"
+    local header library
+
+    # ----------------------------------
+    if isNone "$prefix"
     then
-        [ -n "$warn" ] && echo "$warn (not available)"
+        [ -n "$warn" ] && echo "$warn (disabled)"
         return 1
-    fi
-
-
-    # Header/library names
-    header="scotch.h"
-    library="libscotch$extLibso"
-    static="libscotch$extLiba"
-
-
-    if hasAbsdir "$SCOTCH_ARCH_PATH"
-    then
-        header=$(findFirstFile $SCOTCH_ARCH_PATH/include/$header)
-
-        library=$(findFirstFile \
-            "$(thirdExtLib $library)" \
-            $SCOTCH_ARCH_PATH/lib/$static \
-            $SCOTCH_ARCH_PATH/lib/$library \
-            $SCOTCH_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/$static \
-            $SCOTCH_ARCH_PATH/lib$WM_COMPILER_LIB_ARCH/$library \
-        )
-    elif isSystem "$SCOTCH_ARCH_PATH"
+    elif hasAbsdir "$prefix"
     then
         header=$(findFirstFile \
-            /usr/local/include/$header \
-            /usr/local/include/scotch/$header \
-            /usr/include/$header \
-            /usr/include/scotch/$header \
+            "$prefix/include/$localDir/$incName" \
+            "$prefix/include/scotch/$incName" \
+            "$prefix/include/$incName" \
         )
-
-        case "$header" in
-        /usr/local/*)
-            library=$(findFirstFile \
-                /usr/local/lib/$library \
-                /usr/local/lib$WM_COMPILER_LIB_ARCH/$library \
-            )
-            ;;
-
-        *)
-            library=$(findFirstFile \
-                /usr/lib/$library \
-                /usr/lib$WM_COMPILER_LIB_ARCH/$library \
-            )
-            ;;
-        esac
+        library=$(findExtLib "$libName")
+    elif isSystem "$prefix"
+    then
+        header=$(findFirstFile \
+            "/usr/local/include/$localDir/$incName" \
+            "/usr/local/include/scotch/$incName" \
+            "/usr/local/include/$incName" \
+            "/usr/include/$localDir/$incName" \
+            "/usr/include/scotch/$incName" \
+            "/usr/include/$incName" \
+        )
+        prefix=$(sysPrefix "$header")
     else
-        unset header library
+        unset prefix
     fi
+    # ----------------------------------
+    equalBaseName "${header%/*}" "$localDir" || unset localDir
 
-
-    # Header found?
+    # Header
     [ -n "$header" ] || {
         [ -n "$warn" ] && echo "$warn (no header)"
         return 2
     }
 
-    # Library found?
-    [ -n "$library" ] || {
-        [ -n "$warn" ] && echo "$warn (missing library)"
+    # Library
+    [ -n "$library" ] \
+    || library=$(findLibrary -prefix="$prefix" -name="$libName" -local="$localDir") \
+    || {
+        [ -n "$warn" ] && echo "$warn (no library)"
         return 2
     }
 
+    # ----------------------------------
+
+    local label
 
     # Ensure consistent sizes between OpenFOAM and scotch header
     # extract 'typedef int64_t SCOTCH_Num' or equivalent
     label=$(sed -ne \
         's/^.*typedef *\([^ ]*\) *SCOTCH_Num.*/\1/p' \
         "$header")
-    : ${label:=unknown} # Failsafe value
+    : "${label:=unknown}"
 
 
     # No SCOTCH_VERSION set? Try to obtain from header
@@ -159,58 +192,49 @@ have_scotch()
         IFS="."
         [ "$#" -gt 0 ] && echo "scotch-$*"
     )
-    : ${SCOTCH_VERSION:=scotch} # Failsafe value
-
+    : "${SCOTCH_VERSION:=scotch}"  # Failsafe value
 
     case "$WM_LABEL_SIZE:$label" in
     (32:int32_t | 32:int | 64:int64_t | 64:long)
-        echo "Scotch (label=$label) - $SCOTCH_ARCH_PATH"
-        export HAVE_SCOTCH=true
-        export SCOTCH_ARCH_PATH SCOTCH_VERSION
-        export SCOTCH_INC_DIR="${header%/*}"     # Basename
-        export SCOTCH_LIB_DIR="${library%/*}"    # Basename
         ;;
 
-    *)
+    (*)
         if [ -n "$warn" ]
         then
-            echo "$warn (label='$WM_LABEL_SIZE', scotch.h has '$label')"
+            echo "$warn (label='$WM_LABEL_SIZE', ${header##*/} has '$label')"
         fi
         no_scotch
         return 1
         ;;
     esac
+
+    # OK
+    echo "scotch (label=$label) - $prefix"
+    export HAVE_SCOTCH=true
+    export SCOTCH_ARCH_PATH="$prefix"
+    export SCOTCH_INC_DIR="${header%/*}"     # Basename
+    export SCOTCH_LIB_DIR="${library%/*}"    # Basename
+    export SCOTCH_VERSION
 }
 
 
-# Must be called after have_scotch!
+# Search
+# $1 : prefix (*_ARCH_PATH, system, ...)
 #
 # On success, return 0 and export variables
 # -> HAVE_PTSCOTCH, PTSCOTCH_ARCH_PATH, PTSCOTCH_INC_DIR, PTSCOTCH_LIB_DIR
-have_ptscotch()
+search_ptscotch()
 {
-    local prefix header library static settings warn
-    warn="==> skip ptscotch"
+    local warn="==> skip ptscotch"
+    local incName="ptscotch.h"
+    local libName="libptscotch"
+    local localDir="scotch-int$WM_LABEL_SIZE"
 
-    if [ "$HAVE_SCOTCH" != true ]
-    then
-        echo "$warn (no serial scotch available?)"
-        return 1
-    fi
-
-    # Reuse old settings
-    [ -n "$PTSCOTCH_ARCH_PATH" ] || PTSCOTCH_ARCH_PATH="$SCOTCH_ARCH_PATH"
-
-    # Location
-    prefix="$PTSCOTCH_ARCH_PATH"
+    local prefix="${1:-system}"
+    local header library
 
     local mpiPrefix="$MPI_ARCH_PATH"
     local mpiName="${MPI_ARCH_PATH##*/}"
-
-    # Header/library names
-    header="ptscotch.h"
-    library="libptscotch$extLibso"
-    static="libptscotch$extLiba"
 
     # ----------------------------------
     if isNone "$prefix"
@@ -220,62 +244,54 @@ have_ptscotch()
     elif hasAbsdir "$prefix"
     then
         header=$(findFirstFile  \
-            "$prefix/include/$FOAM_MPI/$header" \
-            "$prefix/include/$header" \
-            "$mpiPrefix/include/$header" \
-            "$prefix/include/$mpiName/$header" \
-            "$prefix/include/${mpiName}-$(uname -m)/$header" \
+            "$prefix/include/$FOAM_MPI/$incName" \
+            "$prefix/include/$localDir/$incName" \
+            "$prefix/include/ptscotch/$incName" \
+            "$prefix/include/scotch/$incName" \
+            "$prefix/include/$incName" \
+            "$mpiPrefix/include/$incName" \
+            "$prefix/include/$mpiName/$incName" \
+            "$prefix/include/${mpiName}-$(uname -m)/$incName" \
         )
-
-        library=$(findFirstFile \
-            "$(thirdExtLib $FOAM_MPI/$library)" \
-            "$(thirdExtLib $library)" \
-            "$prefix/lib/$static" \
-            "$prefix/lib/$library" \
-            "$prefix/lib$WM_COMPILER_LIB_ARCH/$static" \
-            "$prefix/lib$WM_COMPILER_LIB_ARCH/$library" \
-        )
-
+        library="$(findExtLib $FOAM_MPI/$libName $libName)"
     elif isSystem "$prefix"
     then
-        prefix=/usr
-
         header=$(findFirstFile \
-            "/usr/local/include/ptscotch/$header" \
-            "/usr/local/include/scotch/$header" \
-            "/usr/local/include/$header" \
-            "/usr/include/ptscotch/$header" \
-            "/usr/include/scotch/$header" \
-            "/usr/include/$header" \
-            "$mpiPrefix/include/$header" \
-            "/usr/include/$mpiName/$header" \
-            "/usr/include/${mpiName}-$(uname -m)/$header" \
+            "/usr/local/include/$localDir/$incName" \
+            "/usr/local/include/ptscotch/$incName" \
+            "/usr/local/include/scotch/$incName" \
+            "/usr/local/include/$incName" \
+            "/usr/include/$localDir/$incName" \
+            "/usr/include/ptscotch/$incName" \
+            "/usr/include/scotch/$incName" \
+            "/usr/include/$incName" \
+            "$mpiPrefix/include/$incName" \
+            "/usr/include/$mpiName/$incName" \
+            "$prefix/include/${mpiName}-$(uname -m)/$incName" \
         )
-
-        case "$header" in (/usr/local/*) prefix=/usr/local ;; esac
-
-        library=$(findFirstFile \
-            "$prefix/lib/$library" \
-            "$prefix/lib$WM_COMPILER_LIB_ARCH/$library" \
-            "$mpiPrefix/lib/$library" \
-            "$mpiPrefix/lib$WM_COMPILER_LIB_ARCH/$library" \
-        )
+        prefix=$(sysPrefix "$header")
     else
-        unset prefix header library
+        unset prefix
     fi
     # ----------------------------------
+    equalBaseName "${header%/*}" "$localDir" || unset localDir
 
-    # Header found?
+    # Header
     [ -n "$header" ] || {
         [ -n "$warn" ] && echo "$warn (no header)"
         return 2
     }
 
-    # Library found?
-    [ -n "$library" ] || {
+    # Library
+    [ -n "$library" ] \
+    || library=$(findLibrary -prefix="$prefix" -name="$libName" -local="$localDir") \
+    || library=$(findLibrary -prefix="$mpiPrefix" -name="$libName" -local="$localDir") \
+    || {
         [ -n "$warn" ] && echo "$warn (no library)"
         return 2
     }
+
+    # ----------------------------------
 
     # OK
     echo "ptscotch - $prefix"
@@ -286,14 +302,74 @@ have_ptscotch()
 }
 
 
-# Force reset of old variables
+# Output as per search_* function
+have_scotch()
+{
+    local warn="==> skip scotch"
+    local config="config.sh/scotch"
+    local file
+
+    if file="$("$WM_PROJECT_DIR"/bin/foamEtcFile "$config")"
+    then
+        . "$file"
+    else
+        [ -n "$warn" ] && echo "$warn (no $config)"
+        return 2
+    fi
+
+    search_scotch "$SCOTCH_ARCH_PATH"
+}
+
+
+# Output as per search_* function
+have_ptscotch()
+{
+    local warn="==> skip ptscotch"
+
+    if [ "$HAVE_SCOTCH" != true ]
+    then
+        echo "$warn (no serial scotch available?)"
+        return 1
+    fi
+
+    # Reuse old settings
+    [ -n "$PTSCOTCH_ARCH_PATH" ] || PTSCOTCH_ARCH_PATH="$SCOTCH_ARCH_PATH"
+
+    search_ptscotch "$PTSCOTCH_ARCH_PATH"
+}
+
+
+# Query settings
+query_scotch()
+{
+    local config="config.sh/scotch"
+    local file
+
+    if file="$("$WM_PROJECT_DIR"/bin/foamEtcFile -mode=o "$config")"
+    then
+        . "$file"
+        _process_query scotch "$SCOTCH_ARCH_PATH"
+    else
+        echo "(no $config)" 1>&2
+        echo "scotch=unknown"
+    fi
+}
+
+
+#------------------------------------------------------------------------------
+
+# Reset
 no_scotch
 
-# Testing
-if [ "$1" = "-test" ]
-then
+# Test/query
+case "$1" in
+-test)
     have_scotch && have_ptscotch
     echo_scotch
-fi
+    ;;
+-query)
+    query_scotch
+    ;;
+esac
 
 #------------------------------------------------------------------------------
